// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCs1di0_rP42XmDACL0KB8-GyPau1rGVE',
    appId: '1:633449006326:web:0cee9447968a45fe9c98d7',
    messagingSenderId: '633449006326',
    projectId: 'kitahack-2026-836f8',
    authDomain: 'kitahack-2026-836f8.firebaseapp.com',
    storageBucket: 'kitahack-2026-836f8.firebasestorage.app',
    measurementId: 'G-FME8SLYTWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYGF2ucke7Unu-cqqSyJFkKfkv1G5o6sU',
    appId: '1:633449006326:android:5cd234d95f69a8049c98d7',
    messagingSenderId: '633449006326',
    projectId: 'kitahack-2026-836f8',
    storageBucket: 'kitahack-2026-836f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdFMaaEKkEV-T092erpMveb9qBMKhTV8',
    appId: '1:633449006326:ios:9043e6ef7e56feee9c98d7',
    messagingSenderId: '633449006326',
    projectId: 'kitahack-2026-836f8',
    storageBucket: 'kitahack-2026-836f8.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdFMaaEKkEV-T092erpMveb9qBMKhTV8',
    appId: '1:633449006326:ios:9043e6ef7e56feee9c98d7',
    messagingSenderId: '633449006326',
    projectId: 'kitahack-2026-836f8',
    storageBucket: 'kitahack-2026-836f8.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCs1di0_rP42XmDACL0KB8-GyPau1rGVE',
    appId: '1:633449006326:web:d3ae27bc88639c3d9c98d7',
    messagingSenderId: '633449006326',
    projectId: 'kitahack-2026-836f8',
    authDomain: 'kitahack-2026-836f8.firebaseapp.com',
    storageBucket: 'kitahack-2026-836f8.firebasestorage.app',
    measurementId: 'G-FZ1BB5E8GJ',
  );
}
